"""Background audit core logic — pure functions, no IO."""

from app.core.background_audit.candidate_metrics import (
    avg_confidence,
    evidence_quality,
    novelty_to_float,
)
from app.core.background_audit.dataset_prep import (
    RunWindow,
    build_cohort_query,
    compute_run_fingerprint,
    compute_text_hash,
    compute_unit_id,
    compute_window,
    extract_reasoning_units,
    generate_run_id,
    normalize_text,
    validate_quality,
    validate_window,
)
from app.core.background_audit._pii_stubs import mask_pii, scan_text_for_pii
from app.core.background_audit.merge_logic import (
    initialize_dedupe_metadata,
    merge_candidate_card,
    should_skip_pattern,
)
from app.core.background_audit.pattern_analysis import (
    ClusterResult,
    NoveltyResult,
    assign_clusters,
    assign_to_nearest_prototype,
    calculate_candidate_quality,
    compute_centroid,
    detect_novelty,
    meets_quality_gate,
    rank_evidence,
)
from app.core.background_audit.pattern_card import (
    extract_agent_fields,
    extract_sql_query,
    friendly_source_label,
    trace_sql_findings,
)
from app.core.background_audit.signature_matching import (
    CandidateSignature,
    build_candidate_signature,
    match_duplicate_candidate,
    merge_signatures,
)
from app.core.background_audit.text_normalization import (
    as_text,
    dedupe_dict_rows,
    extract_theme_set,
    is_skippable_pattern,
    normalize_sql_findings,
    normalize_web_references,
    safe_float,
    tokenize_keywords,
)

__all__ = [
    "CandidateSignature",
    "ClusterResult",
    "NoveltyResult",
    "RunWindow",
    "as_text",
    "assign_clusters",
    "assign_to_nearest_prototype",
    "avg_confidence",
    "build_candidate_signature",
    "build_cohort_query",
    "calculate_candidate_quality",
    "compute_centroid",
    "compute_run_fingerprint",
    "compute_text_hash",
    "compute_unit_id",
    "compute_window",
    "dedupe_dict_rows",
    "detect_novelty",
    "evidence_quality",
    "extract_agent_fields",
    "extract_reasoning_units",
    "extract_sql_query",
    "extract_theme_set",
    "friendly_source_label",
    "generate_run_id",
    "initialize_dedupe_metadata",
    "is_skippable_pattern",
    "mask_pii",
    "match_duplicate_candidate",
    "meets_quality_gate",
    "merge_candidate_card",
    "merge_signatures",
    "normalize_sql_findings",
    "normalize_text",
    "normalize_web_references",
    "novelty_to_float",
    "rank_evidence",
    "safe_float",
    "scan_text_for_pii",
    "should_skip_pattern",
    "tokenize_keywords",
    "trace_sql_findings",
    "validate_quality",
    "validate_window",
]
