"""add is_fraud to withdrawals drop risk_level from customers

Revision ID: 94d674dd2b1c
Revises: b36343356fa7
Create Date: 2026-02-07 09:49:40.015025
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d674dd2b1c'
down_revision: Union[str, None] = 'b36343356fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'risk_level')
    op.add_column('withdrawals', sa.Column('is_fraud', sa.Boolean(), nullable=True))
    op.add_column('withdrawals', sa.Column('fraud_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'fraud_notes')
    op.drop_column('withdrawals', 'is_fraud')
    op.add_column('customers', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
