"""add_feedback_loop_tables

Revision ID: 9c1a887c5cf8
Revises: 9b424d24c8c8
Create Date: 2026-02-09 22:04:37.232597
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c1a887c5cf8'
down_revision: Union[str, None] = '9b424d24c8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_weight_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blend_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recalculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cwp_customer_active', 'customer_weight_profiles', ['customer_id', 'is_active'], unique=False)
    op.add_column('fraud_patterns', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.add_column('fraud_patterns', sa.Column('evaluation_id', sa.Uuid(), nullable=True))
    op.add_column('fraud_patterns', sa.Column('signal_type', sa.String(length=20), nullable=True))
    op.add_column('fraud_patterns', sa.Column('indicator_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_fp_customer_signal', 'fraud_patterns', ['customer_id', 'signal_type'], unique=False)
    op.create_foreign_key(None, 'fraud_patterns', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'fraud_patterns', 'evaluations', ['evaluation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fraud_patterns', type_='foreignkey')
    op.drop_constraint(None, 'fraud_patterns', type_='foreignkey')
    op.drop_index('ix_fp_customer_signal', table_name='fraud_patterns')
    op.drop_column('fraud_patterns', 'indicator_scores')
    op.drop_column('fraud_patterns', 'signal_type')
    op.drop_column('fraud_patterns', 'evaluation_id')
    op.drop_column('fraud_patterns', 'customer_id')
    op.drop_index('ix_cwp_customer_active', table_name='customer_weight_profiles')
    op.drop_table('customer_weight_profiles')
    # ### end Alembic commands ###
