"""initial schema

Revision ID: b36343356fa7
Revises: 
Create Date: 2026-02-07 15:46:21.949721
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b36343356fa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('fraud_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('indicator_combination', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approve_below', sa.Float(), nullable=False),
    sa.Column('escalate_below', sa.Float(), nullable=False),
    sa.Column('indicator_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=30), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('screen_resolution', sa.String(length=20), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_customer_id', 'devices', ['customer_id'], unique=False)
    op.create_index('ix_devices_fingerprint', 'devices', ['fingerprint'], unique=False)
    op.create_table('ip_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_history_customer_last_seen', 'ip_history', ['customer_id', 'last_seen_at'], unique=False)
    op.create_index('ix_ip_history_ip_address', 'ip_history', ['ip_address'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('last_four', sa.String(length=10), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_methods_customer_type', 'payment_methods', ['customer_id', 'type'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_customer_opened', 'trades', ['customer_id', 'opened_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_customer_ts', 'transactions', ['customer_id', 'timestamp'], unique=False)
    op.create_index('ix_transactions_customer_type', 'transactions', ['customer_id', 'type'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_account', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_withdrawals_customer_requested', 'withdrawals', ['customer_id', 'requested_at'], unique=False)
    op.create_index('ix_withdrawals_status', 'withdrawals', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('withdrawal_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('top_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_is_read', 'alerts', ['is_read'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('withdrawal_id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_withdrawal_id', 'feedback', ['withdrawal_id'], unique=False)
    op.create_table('indicator_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('withdrawal_id', sa.Uuid(), nullable=False),
    sa.Column('indicator_name', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indicator_results_withdrawal_name', 'indicator_results', ['withdrawal_id', 'indicator_name'], unique=False)
    op.create_table('withdrawal_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('withdrawal_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=15), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('withdrawal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_decisions')
    op.drop_index('ix_indicator_results_withdrawal_name', table_name='indicator_results')
    op.drop_table('indicator_results')
    op.drop_index('ix_feedback_withdrawal_id', table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_alerts_is_read', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_withdrawals_status', table_name='withdrawals')
    op.drop_index('ix_withdrawals_customer_requested', table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index('ix_transactions_customer_type', table_name='transactions')
    op.drop_index('ix_transactions_customer_ts', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_trades_customer_opened', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_payment_methods_customer_type', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index('ix_ip_history_ip_address', table_name='ip_history')
    op.drop_index('ix_ip_history_customer_last_seen', table_name='ip_history')
    op.drop_table('ip_history')
    op.drop_index('ix_devices_fingerprint', table_name='devices')
    op.drop_index('ix_devices_customer_id', table_name='devices')
    op.drop_table('devices')
    op.drop_table('threshold_config')
    op.drop_table('fraud_patterns')
    op.drop_table('customers')
    # ### end Alembic commands ###
